jupyterhub:
  hub:
    baseUrl: /jupyterhub/

# BinderHub config
config:
  BinderHub:
    use_registry: true
    image_prefix: srcdev/binder-dev-
    hub_url: http://130.246.214.144/jupyterhub/
    base_url: /binderhub/

service:
  type: NodePort