proxy:
  secretToken: "9495069fe618da99744a1adce9a2a11bd05b89918f09228ad158281c1cd31dd5"
  service:
    type: LoadBalancer
    loadBalancerIP: 130.246.212.44

hub:
  cookieSecret: "0055915cda0071fb868952680f06035fb92a6c25e802d565706fcfe4a649a139"
  db:
    url: postgres+psycopg2://postgres:postgres@pgdatabase-postgresql.pgdatabase.svc.cluster.local:5432/jupyterhubdb
    type: postgres
    password: postgres
  extraEnv:
    OAUTH2_AUTHORIZE_URL: https://iris-iam.stfc.ac.uk/authorize
    OAUTH2_TOKEN_URL: https://iris-iam.stfc.ac.uk/token
    OAUTH_CALLBACK_URL: http://130.246.212.44/hub/oauth_callback

singleuser:
  cpu:
    limit: 2
    guarantee: 1
  memory:
    limit: 5G
    guarantee: 1G
  storage:
    capacity: 6Gi
    dynamic:
      storageClass: "nfs"
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: '0.8.2'
    pullPolicy: IfNotPresent
  profileList:
    - display_name: "Default"
      description: "The default image"
      default: true
    - display_name: "Jupyter data science notebook"
      description: "data science env"
      kubespawner_override:
        image: jupyter/datascience-notebook:latest

auth:
  type: custom
  custom:
      className: oauthenticator.generic.GenericOAuthenticator
      config:
        login_service: "IRIS IAM"
        client_id: "a4d5d04e-9a78-41fc-b3ef-38cf113f3d46"
        client_secret: "<redacted>"
        token_url: https://iris-iam.stfc.ac.uk/token
        userdata_url: https://iris-iam.stfc.ac.uk/userinfo
        userdata_method: GET
        userdata_params: {'state': 'state'}
        username_key: preferred_username
        oauth_callback_url: "http://130.246.212.44/hub/oauth_callback"

cull:
  enabled: true
  timeout: 1800
  every: 300
