apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-nfs-server-provisioner-0
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/volumes/data-nfs-nfs-server-provisioner-0
  claimRef:
    namespace: nfsprovisioner
    name: data-nfs-nfs-server-provisioner-0