proxy:
  secretToken: "232689b2225022bfb20ec19ea4aa9dec934e31ebbceabcb48b2e1ea8340655ee"
  service:
    type: NodePort 

# Running a local network private registry to bypass Docker pull rate limits
# Remove this section and references to 'image-pull-secret' in the yaml if you are not pointing to a registry
imagePullSecret:
  create: true
  registry: 192.168.50.97:5000
  username: admin
  password: <redacted>

hub:
  baseUrl: /escape
  cookieSecret: "d890a4d5f9b93dc13e42e9fc4fed4e2485cf36902fe4cc9a0bd9ddcc5c4006cd"
  image:
    name: 192.168.50.97:5000/jupyterhub/k8s-hub
    tag: '0.11.0'
    pullSecrets:
     - "image-pull-secret"
  db:
    url: postgres+psycopg2://postgres:PoStGrEs@pgdatabase-postgresql.pgdatabase.svc.cluster.local:5432/jhubdb
    type: postgres
    password: postgres
  config:
    GenericOAuthenticator:
      login_service: "ESCAPE IAM"
      client_id: "<redacted>"
      client_secret: "<redacted>"
      token_url: https://iam-escape.cloud.cnaf.infn.it/token
      userdata_url: https://iam-escape.cloud.cnaf.infn.it/userinfo
      userdata_method: GET
      userdata_params: {'state': 'state'}
      username_key: preferred_username
      oauth_callback_url: "https://srcdev.skatelescope.org/escape/hub/oauth_callback"
    JupyterHub:
      authenticator_class: generic-oauth

singleuser:
  cpu:
    limit: 2
    guarantee: 0.5 
  memory:
    limit: 5G
    guarantee: 1G
  storage:
    capacity: 6Gi
    dynamic:
      storageClass: "nfs"
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: '0.11.0'
    pullPolicy: IfNotPresent
    pullSecrets:
     - "image-pull-secret"
  profileList:
    - display_name: "Default"
      description: "The default image"
      default: true
    - display_name: "Jupyter data science notebook"
      description: "data science env"
      kubespawner_override:
        image: jupyter/datascience-notebook:latest
    - display_name: "ESCAPE rucio datalake notebook"
      description: "ESCAPE enabled rucio datalake notebook"
      kubespawner_override:
        image: projectescape/rucio-jupyterhub
        image_pull_policy: Always
        default_url: /lab
        environment:
          RUCIO_MODE: download
          RUCIO_WILDCARD_ENABLED: "1"
          RUCIO_BASE_URL: "https://escape-rucio.cern.ch:32300"
          RUCIO_AUTH_URL: "https://escape-rucio.cern.ch:32301"
          RUCIO_DISPLAY_NAME: ESCAPE
          RUCIO_NAME: ESCAPE
          RUCIO_SITE_NAME: ESCAPE
          RUCIO_VOMS_ENABLED: "1"
          RUCIO_VOMS_VOMSES_PATH: "/etc/vomses"
          RUCIO_VOMS_CERTDIR_PATH: "/etc/grid-security/certificates"
          RUCIO_VOMS_VOMSDIR_PATH: "/etc/grid-security/vomsdir"
          RUCIO_CA_CERT: "/etc/grid-security/certificates/CERN-Root-2.pem"

cull:
  enabled: true
  timeout: 1800
  every: 300
